# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers
      - image: postgres
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/postgres:9.6-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: laravel1db
          
    
    steps:
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip

     # - run:
     #     name: "Create Environment file"
     #     command: |
      #       .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      #- run:
      #    name: Install PHPUnit
       #   command: |
        #    sudo wget -O /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-6.5.phar
         #   sudo chmod +x /usr/local/bin/phpunit

       #run tests with phpunit
      #- run:
       #   name: "Run Unit Tests"
        #  command: ./vendor/bin/phpunit tests/Unit

      - run:
          name: "Create database and run migration"
          command: |
            sudo apt install -y postgresql-client 
            createdb -h 127.0.0.1 laravel1db -O postgres
            php artisan migrate
          


     # - run:
      #    name: "Run Http Tests"
       #   command: ./vendor/bin/phpunit tests/Feature
        #  background: true

      - run:
          name: "Install Dusk and Update Chrome Drivers"
          command: |
            composer require --dev laravel/dusk
            composer require --dev staudenmeir/dusk-updater
            

      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve
          
          

      - run:
          name: Run Browser Tests Tests
          command: php artisan dusk
         
